name: Convert Markdown to PDF

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Convert Markdown to PDF
        run: docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace pandoc/latex:2.9 \ 
          -V colorlinks=true \
          -V linkcolor=blue \
          -V urlcolor=blue \
          -V toccolor=gray \
          README.md -o README.pdf
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: converted-pdf
          path: README.pdf
